name: pesantren_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  flutter_svg: 0.22.0
  shimmer: ^2.0.0
  alice_lightweight: ^3.0.0
  flutter_inappwebview: ^5.3.2
  permission_handler: ^8.3.0
  path_provider: ^2.0.8
  android_path_provider: ^0.3.0
  flutter_typeahead: ^4.0.0
  tree_view: ^0.0.6
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
